apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: function
  namespace: default
spec:
  template:
    spec:
      containers:
        - image: dev.local/function
          livenessProbe:
            httpGet:
              path: /actuator/info
          readinessProbe:
            httpGet:
              path: /actuator/health
