apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: function
spec:
  template:
    spec:
      containers:
        - image: dev.local/function
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
